# All csv files used 
allRaces <- read.csv("498_data/Tab01-AllRaces.csv")
asian <- read.csv("498_data/Tab01-AsianAlone.csv")
asianCombo <- read.csv("498_data/Tab01-AsianAloneOrInCombination.csv")
black <- read.csv("498_data/Tab01-BlackAlone.csv")
blackCombo <- read.csv("498_data/Tab01-BlackAloneOrInCombination.csv")
cFB <- read.csv("498_data/Tab01-ChildrenOfForeignBorn.csv")
foreign <- read.csv("498_data/Tab01-ForeignBorn.csv")
hispanic <- read.csv("498_data/Tab01-Hispanic.csv")
white <- read.csv("498_data/Tab01-WhiteAlone.csv")
whiteNonH <- read.csv("498_data/Tab01-WhiteAloneNonHispanic.csv")
whiteCombo <- read.csv("498_data/Tab01-WhiteAloneOrInCombination.csv")
whiteComboNonH <- read.csv("498_data/Tab01-WhiteAloneOrInCombinationNonHispanic.csv")